M48
; DRILL file KiCad 10.0.4 date 2026-08-05T11:05:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-05T11:05:32+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X18.5Y-5.5
X19.0Y-86.0
X30.5Y-18.0
X30.5Y-41.0
X66.5Y-18.0
X66.5Y-41.0
X90.0Y-5.0
X90.0Y-82.0
M30
