"""Pre-route dense compact-board nets before the general routing pass."""

from __future__ import annotations

from pathlib import Path

import pcbnew

import route_door8ch_final_gaps as grid
import route_door8ch_power_good_hold_up as router


ROOT = Path(__file__).resolve().parents[1]
PCB = ROOT / "hardware" / "UNIVERSAL-2CH" / "kicad" / "UNIVERSAL-2CH.kicad_pcb"
SOURCE = ROOT / "hardware" / "WINDOW-4CH" / "kicad" / "WINDOW-4CH.kicad_pcb"
board = pcbnew.LoadBoard(str(PCB))
source = pcbnew.LoadBoard(str(SOURCE))

grid.GRID = 0.25
grid.CLEARANCE = 0.30
grid.PAD_EXTRA = 0.50
grid.EDGE = 0.75


def pad(reference, number):
    return board.FindFootprintByReference(reference).FindPadByNumber(str(number))


def xy(item):
    point = item if isinstance(item, pcbnew.VECTOR2I) else item.GetPosition()
    return round(pcbnew.ToMM(point.x), 4), round(pcbnew.ToMM(point.y), 4)


def layer(item):
    if item.GetAttribute() == pcbnew.PAD_ATTRIB_PTH:
        return None
    return pcbnew.F_Cu if item.IsOnLayer(pcbnew.F_Cu) else pcbnew.B_Cu


def connect(net_name, a_ref, a_pin, b_ref, b_pin, width=0.20):
    first = pad(a_ref, a_pin)
    second = pad(b_ref, b_pin)
    router.route_multilayer(
        board,
        net_name,
        xy(first),
        xy(second),
        width,
        layer(first),
        pcbnew.F_Cu if layer(second) is None else layer(second),
        second.GetAttribute() == pcbnew.PAD_ATTRIB_PTH,
    )


def path(net_name, copper_layer, points, width=0.20):
    for first, second in zip(points, points[1:]):
        if first != second:
            router.add_track(board, net_name, copper_layer, first, second, width)


def via(net_name, point, diameter=0.70, drill=0.35):
    router.add_via(board, net_name, point, diameter, drill)


# Replace the source board's left-edge CH1_INA detour; that old corridor now
# belongs to the removable sensor and CAN connectors.
for item in list(board.GetTracks()):
    if item.GetNetname() != "CH1_INA":
        continue
    if isinstance(item, pcbnew.PCB_VIA):
        px = pcbnew.ToMM(item.GetPosition().x)
        if abs(px - 18.5) > 0.01:
            board.Delete(item)
    elif item.GetLayer() == pcbnew.In2_Cu:
        board.Delete(item)
    else:
        points = (item.GetStart(), item.GetEnd())
        if any(abs(pcbnew.ToMM(point.x) - 6.9) < 0.01 for point in points):
            board.Delete(item)
ina_escape = (8.0, 31.0)
path("CH1_INA", pcbnew.F_Cu, (xy(pad("U1", 4)), ina_escape))
via("CH1_INA", ina_escape)
path(
    "CH1_INA", pcbnew.In2_Cu,
    (
        ina_escape, (10.0, 33.0), (10.0, 35.0), (8.0, 37.0),
        (8.0, 49.5), (6.8, 50.7), (6.8, 55.3),
        (9.5, 58.0), (9.5, 72.0), (18.5, 72.0), (18.5, 66.0),
    ),
)


# Copy only the proven local VNH DIAG fan-outs. These traces escape between the
# MultiSense pins and cannot be generated by a coarse grid router.
for net_name in ("CH1_DIAG", "CH2_DIAG"):
    for item in source.GetTracks():
        if item.GetNetname() != net_name:
            continue
        points = [item.GetPosition()] if isinstance(item, pcbnew.PCB_VIA) else [
            item.GetStart(), item.GetEnd()
        ]
        if max(pcbnew.ToMM(point.y) for point in points) > 73.0:
            continue
        if isinstance(item, pcbnew.PCB_VIA):
            clone = pcbnew.PCB_VIA(board)
            clone.SetNet(board.FindNet(net_name))
            clone.SetPosition(item.GetPosition())
            clone.SetWidth(item.GetWidth(item.TopLayer()))
            clone.SetDrill(item.GetDrillValue())
            clone.SetLayerPair(item.TopLayer(), item.BottomLayer())
        else:
            clone = pcbnew.PCB_TRACK(board)
            clone.SetNet(board.FindNet(net_name))
            clone.SetLayer(item.GetLayer())
            clone.SetWidth(item.GetWidth())
            clone.SetStart(item.GetStart())
            clone.SetEnd(item.GetEnd())
        board.Add(clone)

# Drop one obsolete dangling source-board tail.
for item in list(board.GetTracks()):
    if isinstance(item, pcbnew.PCB_VIA) or item.GetNetname() != "CH1_DIAG":
        continue
    ends = (xy(item.GetStart()), xy(item.GetEnd()))
    if (17.0, 69.0) in ends:
        board.Delete(item)

# Straight local SOIC fan-outs.
path(
    "EEPROM_CS", pcbnew.F_Cu,
    (xy(pad("R260", 1)), (37.0, 76.825), (38.27, 78.095), xy(pad("U250", 1))),
)
path(
    "EEPROM_WP", pcbnew.F_Cu,
    (xy(pad("R261", 1)), (37.0, 81.825), (38.19, 80.635), xy(pad("U250", 3))),
)
hold_left = (38.0, 86.825)
hold_right = (46.5, 79.365)
path("EEPROM_HOLD", pcbnew.F_Cu, (xy(pad("R262", 1)), hold_left))
via("EEPROM_HOLD", hold_left)
via("EEPROM_HOLD", hold_right)
path("EEPROM_HOLD", pcbnew.B_Cu, (hold_left, (46.5, 86.825), hold_right))
path("EEPROM_HOLD", pcbnew.F_Cu, (hold_right, xy(pad("U250", 7))))

# Shared SPI bus with one dedicated layer per signal.
spi = (
    ("CAP_MOSI", 5, (48.0, 81.905), pcbnew.In1_Cu, 7, 14),
    ("CAP_SCK", 6, (48.0, 80.635), pcbnew.In2_Cu, 8, 2),
    ("CAP_MISO", 2, (37.0, 79.365), pcbnew.B_Cu, 17, 1),
)
for net_name, eeprom_pin, hub, copper_layer, module_pin, cap_pin in spi:
    path(net_name, pcbnew.F_Cu, (xy(pad("U250", eeprom_pin)), hub))
    via(net_name, hub)
    grid.route(board, net_name, copper_layer, hub, xy(pad("MOD1", module_pin)), 0.20)
    grid.route(board, net_name, copper_layer, hub, xy(pad("CAP1", cap_pin)), 0.20)

# Route the DIAG trunks after SPI, so the sensor buses retain their dedicated
# straight corridors.
for channel, module_pin, resistor, copper_layer in (
    (1, 27, "R1107", pcbnew.In1_Cu),
    (2, 3, "R1207", pcbnew.In2_Cu),
):
    sense = xy(pad(resistor, 1))
    escape = (
        sense[0], sense[1] + 1.5
    ) if channel == 1 else (sense[0] - 2.5, sense[1])
    path(f"CH{channel}_DIAG", pcbnew.F_Cu, (sense, escape))
    via(f"CH{channel}_DIAG", escape)
    grid.route(
        board, f"CH{channel}_DIAG", copper_layer,
        escape, xy(pad("MOD1", module_pin)), 0.20,
    )

jobs = (
    ("EEPROM_CS", "R260", 1, "MOD1", 35, 0.20),
    ("REED_A_IN_PLACE", "MOD1", 38, "J203", 2, 0.20),
)
failures = []
for job in jobs:
    try:
        connect(*job)
        print("Routed", job[0], job[1], job[2], "->", job[3], job[4])
    except RuntimeError as error:
        failures.append((job, str(error)))
        print("DEFERRED", job, error)

pcbnew.ZONE_FILLER(board).Fill(board.Zones())
pcbnew.SaveBoard(str(PCB), board)
print(f"Compact pre-route complete; deferred {len(failures)}")
